### ISSUE TITLE
Can't edit texture/shader names after creating them

### ISSUE THREAD

**Issue by mahalis** [markusmoenig/ShaderMania#2]
First off, thanks for making this app—it looks incredibly handy. Trying it out, I noticed something that seems like a UI issue: there doesn’t seem to be a way to edit the name of a texture or shader after creating it. I’ve tried double-clicking the entry in the sidebar as well as selecting it and hitting Return, but nothing happens. This is in the App Store version (1.0), on macOS Big Sur.

**Comment by markusmoenig** [comment]
Ok thanks. I will have a look. Normally it should pop up a context menu via right click on macOS or long click on iOS.

**Comment by markusmoenig** [comment]
Ok, I fixed this in v1.01, code is in the repo and waiting for review in the AppStores.

**Comment by mahalis** [comment]
That was fast—thank you!
