### ISSUE TITLE
Parameterizing blur size

### ISSUE THREAD

**Issue by dreness** [markusmoenig/ShaderMania#4]
Cool app! Can't wait to see where it goes :)

I attempted to parameterize the blur depth in the blur shader you posted to the shared library, however it seems 'variable length arrays are not supported in Metal':

![image](https://user-images.githubusercontent.com/5242016/124517267-68ec0d80-dd98-11eb-85d1-2a469538983a.jpeg)

I know this kind of thing is possible in general, but I've never implemented it from scratch. Would parameterizing the blur amount require a more substantial refactoring of the blur implementation to avoid the 'no variable length arrays' constraint?

Thanks!

**Comment by markusmoenig** [comment]
Hi,

I guess the thing you could do is to fix the array on the array size for the largest parameter size you want to support and calculate kernel size for the parameter independently.

Does this help ? We need to work around the limitations. Other way would be to pass the array to the shader but this kind of custom data flows to the shader are not yet supported in ShaderMania.

**Comment by dreness** [comment]
> Hi,
> 
> 
> 
> I guess the thing you could do is to fix the array on the array size for the largest parameter size you want to support and calculate kernel size for the parameter independently.
> 
> 
> 
> Does this help ? We need to work around the limitations. Other way would be to pass the array to the shader but this kind of custom data flows to the shader are not yet supported in ShaderMania.

I think it does help, yes - thanks :) If I come up with anything I'll post it the cloud library.
